language: php

php:
  - 7.3

os: linux


before_script:
  - curl --version
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
after_success:
  - sh -c ' php vendor/bin/coveralls -v'